#!/usr/bin/python3

 #1
 #n=input("Enter a number: ")
 #if not n.isdigit():
 #	print("I said a number!")
 #	exit()
 #n=int(n)
 #numbers=[]
 #for i in range(n):
 #	num=int(input(f"Enter a number: {i+1}/{n}: "))
 #	numbers.append(num)
 #print(f"Max={max(numbers)}")
  
 #2
 #n=int(input("Enter a number: "))
 #a,b=0,1
 #for i in range(n):
 #	a,b=b,a+b
 #print(a)

 #3
 #sentence=input("Enter a sentence: ")
 #alpha=[]
 #for i in sentence:
 #    if i.isalpha() and i not in alpha:
 #        alpha+=i
 #print(alpha)

 #4
 #nstr=[]
 #while True:
 #	num=input("Enter a number: ('stop'=end): ").lower()
 #	if num=="done":
 #    	break
 #	if not num.isdigit():
 #    	print("I said a number!")
 #    	exit()
 #	nstr.append(num)
 #print(sorted(nstr))

 #5
 #sentence=input("Enter a sentence: ")
 #nstr=[len(word) for word in sentence.split()]
 #print(nstr)

 #6
 #square=[x**2 for x in range(1,11)]
 #print(square)

 #7
 #mstr=[x for x in range(100,1000) if (x//10)%10%2==0]
 #print(mstr)

 #8
 #for x in range(100,1000):
 #	hundreds=x//100
 #	tens=(x//10)%10
 #	ones=x%10
 #	msum=hundreds+tens+ones
 #	if msum>10:
 #        print(x)

 #9
 #n=int(input("Enter a number: "))
 #m=int(input("Enter a number: "))
 #if n<m:
 #	n,m==m,n
 #for i in range(n,m+1):
 #	if i%15==0:
 #        print(f"{i},FizzBuzz")
 #	elif i%5==0:
 #    	print(f"{i},Buzz")
 #	elif i%3==0:
 #    	print(f"{i},Fizz")

 #10
 sentence=input("Enter a sentence: ")
 words=sentence.split()
 if words:
 	long=words[0]
 	for word in words:
     	if len(word)>len(long):
         	long=word
 	print(long)
 else:
 	print("Empty")
  
