#!/usr/bin/python3
#1
#nums=[12,3,5,2,78,4,34,0,192,23]
#ml=[]
#nl=[]
#for i in nums:
#    if i%2==0:
#        ml.append(i)
#    elif i%2!=0:
#        nl.append(i)
#result=sorted(ml)+sorted(nl)
#print(result)

#2
#nums=[x for x in range(1,15)]
#target=25
#print(nums)
#for h in nums:
#    nv=target-h
#    if nv in nums and nums.index(nv)!=nums.index(h):
#        print(nums.index(nv),nums.index(h))
#        continue

#3
#sentence=input("Enter a sentence: ").lower()
#ml=[]
#mmax=0
#for i in sentence:
#    if i.isalpha():
#        count=0
#        for letter in sentence:
#            if letter==i:
#                count+=1
#        if count>mmax:
#            mmax=count
#            ml.append(i)
#print(ml)

#4
#sentence=input("Enter a sentence: ")
#ml=[]
#for i in sentence.split():
#    if i.isalpha() and len(i)>=4:
#            ml.append(i)
#    else:
#        continue
#new_sentence=",".join(ml)
#print(new_sentence)

#5
#sentence=input("Enter a sentence: ")
#ml=[]
#for i in sentence.split():
#    if i.isalpha():
#        ml.append(i[::-1])
#    else:
#        continue
#new_sentence=" ".join(ml)
#print(new_sentence)
