#!/usr/bin/python3
import random

def load_questions(filename):
    questions = []

    try:
        with open(filename, "r", encoding="utf-8") as file:
            lines = file.readlines()

        if not lines:
            print("Sxal: Hrceri fayly fatark e!")
            return []

        for line in lines:
            line = line.strip()

            if not line:
                continue

            if "?" not in line:
                print("Sxal dzevachapov harc!")
                print(line)
                continue

            try:
                q_part, a_part = line.split("?", 1)
                answers = a_part.split(",")

                if len(answers) != 4:
                    print("Sxal patasxanneri qanak!:")
                    continue

                questions.append(line)

            except Exception:
                print("Sxal harci karucvacq!")
                continue

    except FileNotFoundError:
        print(f"Sxal {filename} fayly chi gtnvel։")
        return []

    except PermissionError:
        print("Mutq chka faylin։")
        return []

    except Exception as e:
        print("Sxal:", e)
        return []

    return questions


def parse_question(question):
    q, answers = question.split("?", 1)

    answers = answers.split(",")
    correct = answers[0]

    return q, answers, correct


def show_question(question):
    print("\n" + question + "?")


def show_answers(answers):
    for i, answer in enumerate(answers, start=1):
        print(f"{i}. {answer}")


def user_answer():

    while True:

        try:
            user = input("Patasxan (1-4): ").strip()

            if user == "":
                print("Datark mutqagrum։")
                continue

            if " " in user:
                print("Mutqagreq mek tiv:")
                continue

            user = int(user)

            if user < 1 or user > 4:
                print("Tivy (1-4)։")
                continue

            return user

        except ValueError:
            print("Sxal mutqagreq (1-4)։")


def check_answer(user, answers, correct):

    try:
        if answers[user - 1] == correct:
            print(" Correct!")
            return 1

        else:
            print(" Wrong!")
            print("Correct answer:", correct)
            return 0

    except IndexError:
        print("Sxal։")
        return 0


def ask_question(question):

    try:
        question, answers, correct = parse_question(question)

        random.shuffle(answers)

        show_question(question)
        show_answers(answers)

        user = user_answer()

        return check_answer(user, answers, correct)

    except Exception as e:
        print("Harci sxal:", e)
        return 0


def quiz():

    questions = load_questions("questions.txt")

    if not questions:
        print("Xaxy hnaravor che sksel։")
        return

    score = 0

    random.shuffle(questions)

    total_questions = min(10, len(questions))

    for q in questions[:total_questions]:

        try:
            score += ask_question(q)

        except Exception as e:
            print("Sxal", e)

    print("\n GAME OVER")
    print(f"Score: {score}/{total_questions}")


quiz()
